In [182]:
import pandas as pd
import numpy as np

In [183]:
data=pd.read_csv("crx.data",header=None)

In [184]:
data.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [185]:
data.tail(17)

0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
673  ?  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674  a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675  a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676  a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677  b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678  a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679  a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680  b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682  b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683  b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684  b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685  b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [186]:
data.shape

(690, 16)

In [187]:
data.describe()

2           7          10             14
count  690.000000  690.000000  690.00000     690.000000
mean     4.758725    2.223406    2.40000    1017.385507
std      4.978163    3.346513    4.86294    5210.102598
min      0.000000    0.000000    0.00000       0.000000
25%      1.000000    0.165000    0.00000       0.000000
50%      2.750000    1.000000    0.00000       5.000000
75%      7.207500    2.625000    3.00000     395.500000
max     28.000000   28.500000   67.00000  100000.000000

In [188]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       690 non-null    object 
 1   1       690 non-null    object 
 2   2       690 non-null    float64
 3   3       690 non-null    object 
 4   4       690 non-null    object 
 5   5       690 non-null    object 
 6   6       690 non-null    object 
 7   7       690 non-null    float64
 8   8       690 non-null    object 
 9   9       690 non-null    object 
 10  10      690 non-null    int64  
 11  11      690 non-null    object 
 12  12      690 non-null    object 
 13  13      690 non-null    object 
 14  14      690 non-null    int64  
 15  15      690 non-null    object 
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB


In [189]:
data.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

In [190]:
def check(data):  
  for i in data.columns:
    print(i,':')
    print(data[i].value_counts())
    #'print("\n")

In [191]:
check(data)

0 :
b    468
a    210
?     12
Name: 0, dtype: int64
1 :
?        12
22.67     9
20.42     7
24.50     6
22.50     6
         ..
56.00     1
41.42     1
18.67     1
53.33     1
55.75     1
Name: 1, Length: 350, dtype: int64
2 :
1.500     21
0.000     19
3.000     19
2.500     19
1.250     16
          ..
12.125     1
13.915     1
22.000     1
12.835     1
10.915     1
Name: 2, Length: 215, dtype: int64
3 :
u    519
y    163
?      6
l      2
Name: 3, dtype: int64
4 :
g     519
p     163
?       6
gg      2
Name: 4, dtype: int64
5 :
c     137
q      78
w      64
i      59
aa     54
ff     53
k      51
cc     41
m      38
x      38
d      30
e      25
j      10
?       9
r       3
Name: 5, dtype: int64
6 :
v     399
h     138
bb     59
ff     57
?       9
z       8
j       8
dd      6
n       4
o       2
Name: 6, dtype: int64
7 :
0.000    70
0.250    35
0.040    33
1.000    31
0.125    30
         ..
3.960     1
2.040     1
1.040     1
4.165     1
5.375     1
Name: 7, Length: 132, dtype:

In [192]:
data.replace('?',np.nan,inplace=True) #all ?  replaced by Nan

In [193]:
check(data)

0 :
b    468
a    210
Name: 0, dtype: int64
1 :
22.67    9
20.42    7
24.50    6
22.50    6
25.00    6
        ..
56.00    1
41.42    1
18.67    1
53.33    1
55.75    1
Name: 1, Length: 349, dtype: int64
2 :
1.500     21
0.000     19
3.000     19
2.500     19
1.250     16
          ..
12.125     1
13.915     1
22.000     1
12.835     1
10.915     1
Name: 2, Length: 215, dtype: int64
3 :
u    519
y    163
l      2
Name: 3, dtype: int64
4 :
g     519
p     163
gg      2
Name: 4, dtype: int64
5 :
c     137
q      78
w      64
i      59
aa     54
ff     53
k      51
cc     41
m      38
x      38
d      30
e      25
j      10
r       3
Name: 5, dtype: int64
6 :
v     399
h     138
bb     59
ff     57
z       8
j       8
dd      6
n       4
o       2
Name: 6, dtype: int64
7 :
0.000    70
0.250    35
0.040    33
1.000    31
0.125    30
         ..
3.960     1
2.040     1
1.040     1
4.165     1
5.375     1
Name: 7, Length: 132, dtype: int64
8 :
t    361
f    329
Name: 8, dtype: int64
9 :
f   

In [194]:
data.isnull().sum()

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64

In [195]:
for col in data.select_dtypes(include=np.number).columns.tolist():      #filled numerical missing datas
  data[col].fillna(data[col].mean(),inplace=True)

In [196]:
for col in data.columns:                                                #filled categorical missing datas
  if data[col].dtypes=='object':
    data.fillna(data[col].value_counts().index[0],inplace=True)
data.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

In [197]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for col in data.columns:                                                #filled categorical missing datas
  if data[col].dtypes=='object':
    data[col]=le.fit_transform(data[col])


In [198]:
data.info()     #succesfully converted all categorical data to numerical

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       690 non-null    int64  
 1   1       690 non-null    int64  
 2   2       690 non-null    float64
 3   3       690 non-null    int64  
 4   4       690 non-null    int64  
 5   5       690 non-null    int64  
 6   6       690 non-null    int64  
 7   7       690 non-null    float64
 8   8       690 non-null    int64  
 9   9       690 non-null    int64  
 10  10      690 non-null    int64  
 11  11      690 non-null    int64  
 12  12      690 non-null    int64  
 13  13      690 non-null    int64  
 14  14      690 non-null    int64  
 15  15      690 non-null    int64  
dtypes: float64(2), int64(14)
memory usage: 86.4 KB


In [199]:
from sklearn.model_selection import train_test_split
data=data.drop([11,13], axis=1)
print(data.head())
data=data.values
X,y=data[:,0:12],data[:,13]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

   0    1      2   3   4   5   6     7   8   9   10  12   14  15
0   1  156  0.000   2   1  13   8  1.25   1   1   1   0    0   0
1   0  328  4.460   2   1  11   4  3.04   1   1   6   0  560   0
2   0   89  0.500   2   1  11   4  1.50   1   0   0   0  824   0
3   1  125  1.540   2   1  13   8  3.75   1   1   5   0    3   0
4   1   43  5.625   2   1  13   8  1.71   1   0   0   2    0   0


In [200]:
from sklearn.preprocessing import MinMaxScaler
scalar=MinMaxScaler(feature_range=(0,1))
rescaledX_train=scalar.fit_transform(X_train)
rescaleX_test=scalar.transform(X_test)


In [49]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(rescaledX_train,y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [50]:
pred=logreg.predict(rescaleX_test)
pred

array([1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1.,
       0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0.,
       0., 0., 1., 0., 1.

In [53]:
from sklearn.metrics import confusion_matrix
print("The accuracy of the model is : ",logreg.score(rescaleX_test,y_test))

The accuracy of the model is :  0.8421052631578947


In [54]:
confusion_matrix(y_test,pred)

array([[94,  9],
       [27, 98]])

##Trying different models

####KNN

In [159]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(rescaledX_train,y_train)
y_pred=knn.predict(rescaleX_test)
print("The accuracy of the model is : ",knn.score(rescaleX_test,y_test))
confusion_matrix(y_test,y_pred)


The accuracy of the model is :  0.8728070175438597


array([[ 95,   8],
       [ 21, 104]])

####Decision Tree

In [139]:
from sklearn.ensemble import RandomForestClassifier
rfm=RandomForestClassifier()
rfm.fit(rescaledX_train,y_train)
yrfm_pred=rfm.predict(rescaleX_test)
print("The accuracy of the model is : ",rfm.score(rescaleX_test,y_test))
confusion_matrix(y_test,yrfm_pred)


The accuracy of the model is :  0.868421052631579


array([[ 89,  14],
       [ 16, 109]])

####SVM

In [181]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(rescaledX_train,y_train)
ysvm_pred=svm.predict(rescaleX_test)
print("The accuracy of the model is : ",svm.score(rescaleX_test,y_test))
confusion_matrix(y_test,ysvm_pred)

The accuracy of the model is :  0.8552631578947368


array([[ 91,  12],
       [ 21, 104]])

######OUT OF THE MODELS USED KNN GAVE BETTER RESULT WITH SETTING N_NEIGHBORS AS 4